---
- name: Debug groups
  debug:
    msg: "{{ groups.get('proxy') }}"
  tags:
    - debug

- name: Debug ansible_distribution_release
  debug:
    var: ansible_distribution_release

- name: Install 3proxy deb package from github.com
  apt:
    deb: "https://github.com/3proxy/3proxy/\
          releases/download/{{ proxy_version }}/\
          3proxy-{{ proxy_version }}.{{ ansible_architecture }}.deb"
  tags:
    - install

- name: "Add 3proxy user: {{ proxy_user }}"
  user:
    name: "{{ proxy_user }}"
    group: "{{ proxy_group }}"
    system: true
    shell: /usr/sbin/nologin
    createhome: false
  tags:
    - install

- name: Create config
  template:
    src: 3proxy.cfg.j2
    dest: "{{ proxy_config }}"
    mode: 0644
  notify: Restart 3proxy
  tags:
    - config

- name: Remove old passwd
  file:
    path: "{{ proxy_config_path }}/passwd"
    state: absent
  changed_when: false
  tags:
    - config

- name: Create/update 3proxy passwd file
  ansible.builtin.command:
    argv:
      - /bin/sh
      - /usr/local/3proxy/conf/add3proxyuser.sh
      - '{{ item.username }}'
      - '{{ item.password }}'
  with_items: "{{ proxy_users_list }}"
  no_log: true
  notify: Restart 3proxy
  tags:
    - config

- name: "Ensure access mode 0640 for {{ proxy_config_path }}/passwd"
  file:
    path: "{{ proxy_config_path }}/passwd"
    state: touch
    mode: 0640
    owner: "{{ proxy_user }}"
    group: "{{ proxy_group }}"
  changed_when: false
  tags:
    - config

- name: Enable 3proxy service
  systemd:
    name: 3proxy
    enabled: true
    masked: false
    state: started
  tags:
    - config
