---
- name: Debug groups
  debug:
    msg: "{{ groups.get('proxy') }}"
  tags:
    - debug

- name: Debug ansible_distribution_release
  debug:
    var: ansible_distribution_release

- name: Install 3proxy deb package from github.com
  apt:
    deb: "https://github.com/3proxy/3proxy/\
          releases/download/{{ proxy_version }}/\
          3proxy-{{ proxy_version }}.{{ ansible_architecture }}.deb"
  tags:
    - install

- name: "Add 3proxy user: {{ proxy_user }}"
  user:
    name: "{{ proxy_user }}"
    group: "{{ proxy_group }}"
    system: true
    shell: /usr/sbin/nologin
    createhome: false
  tags:
    - install

- name: Create config
  template:
    src: 3proxy.cfg.j2
    dest: "{{ proxy_config }}"
    mode: 0644
  notify: Restart 3proxy
  tags:
    - config

- name: Create(touch) passwd
  file:
    path: "{{ proxy_config_path }}/passwd"
    state: touch
    mode: 0640
    owner: "{{ proxy_user }}"
    group: "{{ proxy_group }}"
  notify: Restart 3proxy
  tags:
    - config

- name: Enable 3proxy service
  systemd:
    name: 3proxy
    enabled: true
    masked: false
    state: restarted
  tags:
    - config
