---
name: CI

on:
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:
  workflow_run:
    workflows:
      - "code linter"
    branches:
      - master
    types:
      - completed

defaults:
  run:
    working-directory: 'ansible-ipset'

jobs:
  deb:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:10
          - debian:11
          - ubuntu:20.04
          - ubuntu:22.04
        ansible-version:
          - '5.1'
          - '6.1'
        scenario:
          - default

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ipset'

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}

  publish:
    if: github.ref == 'refs/heads/master'
    needs:
      - deb
    runs-on: ubuntu-20.04
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          git_branch: master  # default
